# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deca7c7526cc937c241fc2f5a840552a950754426a1d2a712a2188c8c31e02669d7537100abb95758c8416a553a73d029fca42f6a1e17f2a4220a7683ba45e5f

test:
  secret_key_base: b71a45e173d3e0e7c6cb8e9f41fda1e0559c00ecb9e4317776b22cd45db3ed2e12112f86fcfe05c950f6b8ddd2044a43504f340e3807e59804576f4fe7b859ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
